/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreaFitxes.java
 *
 * Created on 21-jun-2011, 21:46:42
 */

package org.iesapp.modules.fitxes.dialogs.admin;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import javax.swing.Timer;
import org.iesapp.clients.iesdigital.fitxes.BeanDadesPersonals;
import org.iesapp.framework.util.CoreCfg;
import org.iesapp.modules.fitxes.FitxesGUI;
import org.iesapp.modules.fitxescore.util.Cfg;
import org.iesapp.util.StringUtils;

/**
 *
 * @author Josep
 */
public class CreaFitxes extends javax.swing.JDialog {

   
     private DefaultComboBoxModel modelCombo1;
     private DefaultListModel listmodel1;
     private final Timer timer;
     private final int AnimationRate=1000;
     private int status =0;
     private LongTask task;
     private final Cfg cfg;

    /** Creates new form CreaFitxes */
    public CreaFitxes(java.awt.Frame parent, boolean modal, Cfg cfg) {
        super(parent, modal);
        this.cfg = cfg;
        initComponents();

        modelCombo1 = new DefaultComboBoxModel();
        listmodel1 = new DefaultListModel();
        jList1.setModel(listmodel1);


        
        for(int i=0; i<FitxesGUI.modelComboAnys.getSize(); i++)
        {
            modelCombo1.addElement(FitxesGUI.modelComboAnys.getElementAt(i));
        }
        jComboBox1.setModel(modelCombo1);
        jComboBox1.setSelectedItem(cfg.anyAcademicFitxes+"-"+(cfg.anyAcademicFitxes+1));

        timer = new javax.swing.Timer(AnimationRate, new
                ActionListener() {
                         public void actionPerformed(ActionEvent e) {
                                 if(task!=null && task.isAlive())
                                 {
                                    jButton3.setEnabled(false);
                                    jButton2.setEnabled(false);
                                    jButton1.setEnabled(false);
                                 }
                                 else
                                 {
                                    jButton3.setEnabled(true);
                                    jButton2.setEnabled(true);
                                    jButton1.setEnabled(true);
                                    timer.stop();
                                 }
                         }
         });

        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administra i crea fitxes");

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jComboBox1.setName("jComboBox1"); // NOI18N

        jLabel1.setText("Curs Academic");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Alumnes");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("Log");
        jLabel3.setName("jLabel3"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setName("jList1"); // NOI18N
        jScrollPane1.setViewportView(jList1);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane2.setViewportView(jTextArea1);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 60, 5));

        jButton3.setText("Comprova");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton2.setText("Genera les fitxes que falten");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton1.setText("Tanca");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 573, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Alumnes sense fitxa", jPanel1);

        jPanel4.setName("jPanel4"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Fitxes sense alumne", jPanel4);

        jProgressBar1.setName("jProgressBar1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Fitxes sense alumne");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Comprova
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        comprova();
    }//GEN-LAST:event_jButton3ActionPerformed

    
    /**
     * Mèdode estatic:
     * Genera les fitxes que falten a l'any academic, per la llista d'alumnes
     * Si l'alumne de la llista ja té creada la fitxa, no la torna a crear
     * @param anyacademic
     * @param expds
     * @return el nombre de fitxes creades
     */
    public static int generaFitxes(String anyacademic, ArrayList<Integer> expds, Cfg cfg) {
         
        int n = 0;
        
        for(int i=0; i<expds.size(); i++)
        {
            BeanDadesPersonals bean = new BeanDadesPersonals(cfg.getCoreCfg().getIesClient());
            if(!bean.isFitxaCursCreated(expds.get(i), anyacademic))
            {
                bean.createFitxaCurs(expds.get(i), anyacademic);
                n += 1;
            }
                
        }
        return n;        
    }
    
    
    private void comprova()
    {
         listmodel1.removeAllElements();

        String any = (String) jComboBox1.getSelectedItem();
        any = StringUtils.BeforeLast(any, "-");
       

        //QUERY Basada en l'historic
         String SQL1="   SELECT  "+
              "  h.Exp2,  "+
              "  h.AnyAcademic,  "+
              "  h.Ensenyament,  "+
              "  h.Estudis,  "+
              "  h.Grup,  "+
              "  h.ProfTutor,  "+
              "  xal.Llinatge1,  "+
              "  xal.Llinatge2,  "+
              "  xal.Nom1   "+
            "  FROM  `"+CoreCfg.core_mysqlDBPrefix+"`.xes_alumne_historic AS h   "+
              "  INNER JOIN `"+CoreCfg.core_mysqlDBPrefix+"`.xes_alumne AS xal   "+
              "  ON xal.Exp2 = h.Exp2 AND h.AnyAcademic = '"+any+"' "+
            "  WHERE    "+
              "  h.Exp2 NOT IN   "+
              "  (SELECT   "+
              "    a.Exp_FK_ID AS Exp2   "+
              "  FROM  `"+CoreCfg.core_mysqlDBPrefix+"`.fitxa_alumne_curs AS a   "+
              "  WHERE  a.IdCurs_FK_ID = '"+any+"')";


        //System.out.println(SQL1);
 
        int casos=0;
        try {
              Statement st = cfg.getCoreCfg().getMysql().createStatement();
              ResultSet rs1 = cfg.getCoreCfg().getMysql().getResultSet(SQL1,st);
              
            while (rs1 != null && rs1.next()) {
                int expd = rs1.getInt("Exp2");
                String nom = rs1.getString("Llinatge1") + " " + rs1.getString("Llinatge2") +", " +rs1.getString("Nom1");
                listmodel1.addElement(nom+ " ["+expd+"] ");
                casos +=1;
            }
            rs1.close();
            st.close();
        } catch (SQLException ex) {
            Logger.getLogger(CreaFitxes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jTextArea1.append("> Hi ha "+casos+" alumnes sense la fitxa del curs "+any+" creada.\n");
    } 
    
    //Genera
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(task==null || !task.isAlive())
       {
            timer.start();
            comprova();
            task = new LongTask();
            task.start();
       }
       else
       {
            task.interrupt();
       }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(task!=null && task.isAlive()) {
            return;
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    class LongTask extends Thread
    {
    public void run()
    {
        double status = 0;
        double inc = 100./(1.0*listmodel1.getSize());
        String any = (String) jComboBox1.getSelectedItem();

        for(int i=0; i<listmodel1.getSize(); i++)
        {
            status += inc;
            String aux = (String) listmodel1.getElementAt(i);

            aux = StringUtils.BeforeLast(aux, "]");

            aux = StringUtils.AfterLast(aux, "[");

            int exp = (int) Double.parseDouble(aux);
            BeanDadesPersonals bean = new BeanDadesPersonals(cfg.getCoreCfg().getIesClient());
            bean.createFitxaCurs(exp, any);
            jTextArea1.append("> S'ha creat la fitxa de l'alumne "+exp+" per a l'any "+any+".\n");
            jProgressBar1.setValue((int) status);
        }
    }
}

     @Override
    protected JRootPane createRootPane() {
    JRootPane rootPane2 = new JRootPane();
    KeyStroke stroke = KeyStroke.getKeyStroke("ESCAPE");
    Action actionListener = new AbstractAction() {
      public void actionPerformed(ActionEvent actionEvent) {
        setVisible(false);
      }
    } ;
    InputMap inputMap = rootPane2.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
    inputMap.put(stroke, "ESCAPE");
    rootPane2.getActionMap().put("ESCAPE", actionListener);

    return rootPane2;
  }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}



