/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CropImage.java
 *
 * Created on 03-jun-2011, 10:08:09
 */

package org.iesapp.modules.fitxes.forms;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ComponentEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author Josep
 */
public class CropImage extends javax.swing.JDialog {
    private final String mpath;
        private int mwidth;
            private int mheight;

    /** Creates new form CropImage */
    public CropImage(java.awt.Frame parent, boolean modal, String path) {
        super(parent, modal);
        initComponents();

        mpath = path;

                this.addComponentListener(new java.awt.event.ComponentAdapter()
		{

			public void componentResized(ComponentEvent e)
			{
				//System.out.println("JFrame was resized");
                                java.awt.Dimension dim = jLabel2.getSize();
                                Image img = Toolkit.getDefaultToolkit().getImage(mpath);
                                mwidth = img.getWidth(null);
                                mheight = img.getHeight(null);
                                double ratio = mwidth/(1.0*mheight);
                                int heigth2 = dim.height;
                                int width2 = (int) ratio*heigth2;
                                //        Image image = createImage(new FilteredImageSource(img.getSource(),
                                //                     new CropImageFilter(76,201,150,200))); //inici,inici i amplada,amplada
                                Image scaledInstance = img.getScaledInstance(-1, heigth2, Image.SCALE_DEFAULT);

                                jLabel2.setIcon( new ImageIcon(scaledInstance) ); // NOI18N
			}
		});
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        jLabel1.setText("Retalla la imatge");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel2.setName("jLabel2"); // NOI18N

        jButton1.setText("Aplica i Tanca");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
    //
    }//GEN-LAST:event_formWindowStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        org = new java.awt.Point(0,0);
        size = new java.awt.Dimension(mwidth,mheight); //no retalla res
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    public java.awt.Point org;
    public java.awt.Dimension size;
}
