/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormFitxaCurs.java
 *
 * Created on 07-abr-2011, 17:48:44
 */

package org.iesapp.modules.fitxes.forms;


import java.awt.Graphics;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import org.iesapp.clients.iesdigital.fitxes.BeanFitxaCurs;
import org.iesapp.clients.iesdigital.fitxes.SgdInc;
import org.iesapp.framework.data.User;
import org.iesapp.framework.pluggable.grantsystem.Profile;
import org.iesapp.modules.fitxes.FitxesGUI;
import org.iesapp.modules.fitxescore.util.Cfg;
import org.iesapp.util.DataCtrl;
import org.iesapp.util.StringUtils;

/**
 *
 * @author Josep
 */
public class FormFitxaCurs extends javax.swing.JPanel {
    private Cfg cfg;
    private DefaultTableModel modelTable1;
    private DefaultListModel modelList1;
    private boolean isEditable;
    private BeanFitxaCurs bean;
    public int nchanges;
    private String toolTip_imported="";


    /** Creates new form FormFitxaCurs */
    public FormFitxaCurs() {
        initComponents();
        modelList1 = new DefaultListModel();
        jList1.setModel(modelList1);
        jScrollPane5.setViewportView(jTable1);
        jTable1.setToolTipText("Incidències importades SGD");
        

        DefaultComboBoxModel mComboProgrames = new DefaultComboBoxModel();
        DefaultComboBoxModel mComboEnsenyament = new DefaultComboBoxModel();
        DefaultComboBoxModel mComboEstudis = new DefaultComboBoxModel();
        DefaultComboBoxModel mComboGrup = new DefaultComboBoxModel();

        mComboProgrames.addElement("Triau una opció");
        for(int i=0; i<Cfg.modelComboProgrames.size(); i++) {
            mComboProgrames.addElement(Cfg.modelComboProgrames.get(i));
        }

        for(int i=0; i<Cfg.modelComboEnsenyament_tots.size(); i++) {
            mComboEnsenyament.addElement(Cfg.modelComboEnsenyament_tots.get(i));
        }

        for(int i=0; i<Cfg.modelComboEstudis_tots.size(); i++) {
            mComboEstudis.addElement(Cfg.modelComboEstudis_tots.get(i));
        }


        for(int i=0; i<Cfg.modelComboGrup_tots.size(); i++) {
            mComboGrup.addElement(Cfg.modelComboGrup_tots.get(i));
        }


        jComboBox1.setModel(mComboProgrames);
        jEnsenyament.setModel(mComboEnsenyament);
        jEstudis.setModel(mComboEstudis);
        jGrup.setModel(mComboGrup);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int col)
            {
                return false;
            }
        };
        jPanel6 = new javax.swing.JPanel(){

            public void paintComponent(Graphics g)
            {
                java.awt.Dimension d = getSize();
                javax.swing.ImageIcon img = new javax.swing.ImageIcon(getClass().getResource("/org/iesapp/modules/fitxes/icons/fons1.jpg"));
                //Dimension size = new Dimension(img.getWidth(null), img.getHeight(null));
                //setPreferredSize(size);
                //setMinimumSize(size);
                //setMaximumSize(size);
                //setSize(size);
                //setLayout(null);
                for( int x = 0; x < d.width; x += img.getIconWidth() )
                for( int y = 0; y < d.height; y += img.getIconHeight() )
                g.drawImage( img.getImage(), x, y, null, null );

            }
        };

        ;
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jSancions = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jObservacions = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jDerivaORI = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jMotiuDerivacioORI = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jNotaMitjanaFinal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jNumMateriesSuspesesJuny = new com.toedter.components.JSpinField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel8 = new javax.swing.JPanel();
        jDataModificacio = new javax.swing.JLabel();
        jCreador = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jModificat = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        jEstudis = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jGrup = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jEnsenyament = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jProfessor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jAny_academic = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();

        modelTable1 = new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Incidència", "1a Aval", "2a Aval", "3a Aval"
            }
        );
        jTable1.setModel(modelTable1);
        jTable1.setName("jTable1"); // NOI18N

        jPanel6.setName("jPanel6"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Expedients / Sancions"));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setOpaque(false);

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jSancions.setColumns(20);
        jSancions.setLineWrap(true);
        jSancions.setRows(5);
        jSancions.setWrapStyleWord(true);
        jSancions.setName("jSancions"); // NOI18N
        jScrollPane3.setViewportView(jSancions);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Observacions"));
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setOpaque(false);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jObservacions.setColumns(20);
        jObservacions.setLineWrap(true);
        jObservacions.setRows(5);
        jObservacions.setWrapStyleWord(true);
        jObservacions.setName("jObservacions"); // NOI18N
        jScrollPane1.setViewportView(jObservacions);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Orientació"));
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setOpaque(false);

        jDerivaORI.setText("Derivat a orientació");
        jDerivaORI.setName("jDerivaORI"); // NOI18N
        jDerivaORI.setOpaque(false);

        jLabel10.setText("Motiu de la derivació");
        jLabel10.setName("jLabel10"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jMotiuDerivacioORI.setColumns(20);
        jMotiuDerivacioORI.setLineWrap(true);
        jMotiuDerivacioORI.setRows(5);
        jMotiuDerivacioORI.setWrapStyleWord(true);
        jMotiuDerivacioORI.setName("jMotiuDerivacioORI"); // NOI18N
        jScrollPane2.setViewportView(jMotiuDerivacioORI);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jDerivaORI))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jDerivaORI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Notes"));
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setOpaque(false);

        jLabel11.setText("Nota mitjana de juny");
        jLabel11.setName("jLabel11"); // NOI18N

        jNotaMitjanaFinal.setName("jNotaMitjanaFinal"); // NOI18N

        jLabel12.setText("Matèries suspeses juny");
        jLabel12.setName("jLabel12"); // NOI18N

        jNumMateriesSuspesesJuny.setMinimum(0);
        jNumMateriesSuspesesJuny.setName("jNumMateriesSuspesesJuny"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jNumMateriesSuspesesJuny, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(jNotaMitjanaFinal))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(5, 5, 5)
                .addComponent(jNotaMitjanaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNumMateriesSuspesesJuny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Programes"));
        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setOpaque(false);

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setName("jList1"); // NOI18N
        jScrollPane4.setViewportView(jList1);

        jButton1.setText("Esborra");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setName("jComboBox1"); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel8.setName("jPanel8"); // NOI18N

        jDataModificacio.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jDataModificacio.setName("jDataModificacio"); // NOI18N

        jCreador.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jCreador.setName("jCreador"); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel19.setText("Modificat per:");
        jLabel19.setName("jLabel19"); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel17.setText("Creat:");
        jLabel17.setName("jLabel17"); // NOI18N

        jModificat.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jModificat.setName("jModificat"); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCreador, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jModificat, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDataModificacio, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDataModificacio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCreador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jModificat, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3))
        );

        jScrollPane5.setName("jScrollPane5"); // NOI18N

        jPanel9.setName("jPanel9"); // NOI18N
        jPanel9.setOpaque(false);

        jEstudis.setName("jEstudis"); // NOI18N

        jLabel13.setText("Ensenyament");
        jLabel13.setName("jLabel13"); // NOI18N

        jGrup.setName("jGrup"); // NOI18N

        jLabel2.setText("Grup");
        jLabel2.setName("jLabel2"); // NOI18N

        jEnsenyament.setName("jEnsenyament"); // NOI18N

        jLabel4.setText("Estudis");
        jLabel4.setName("jLabel4"); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jEnsenyament, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEstudis, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jGrup, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEstudis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEnsenyament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGrup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jPanel10.setName("jPanel10"); // NOI18N
        jPanel10.setOpaque(false);

        jProfessor.setName("jProfessor"); // NOI18N

        jLabel3.setText("Professor Tutor");
        jLabel3.setName("jLabel3"); // NOI18N

        jAny_academic.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jAny_academic.setText("jLabel2");
        jAny_academic.setName("jAny_academic"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Curs Acadèmic");
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jAny_academic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProfessor)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jAny_academic))
                .addGap(5, 5, 5)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(196, 196, 196))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        jPanel7.setName("jPanel7"); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/iesapp/modules/fitxes/icons/halt.gif"))); // NOI18N
        jLabel16.setText("  No té permisos per veure el contingut");
        jLabel16.setName("jLabel16"); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    //afegeix un programa a la llista
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       if(jComboBox1.getSelectedIndex()<1) {
           return;
       }

       String txt = (String) jComboBox1.getSelectedItem();
       if(!modelList1.contains(txt)){
           modelList1.addElement(txt);
       }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int id =jList1.getSelectedIndex();
        if(id<0) {
            return;
        }
        modelList1.remove(id);
    }//GEN-LAST:event_jButton1ActionPerformed


    public void setData(BeanFitxaCurs b, Cfg cfg)
    {
            this.cfg = cfg;
            bean = b;

            //System.out.println(b.getAny_academic()+b.getCurs()+b.getGrup()+b.getNivell());
            
            jProfessor.setText(b.getProfessor());

            jEstudis.setSelectedItem(b.getCurs());
           
            jGrup.setSelectedItem(b.getGrup());
            jEnsenyament.setSelectedItem(b.getNivell());

            jAny_academic.setText(b.getAny_academic());
            jNotaMitjanaFinal.setText( "" + b.getNotaMitjanaFinal());
            jNumMateriesSuspesesJuny.setValue(b.getNumMateriesSuspesesJuny());
            jDerivaORI.setSelected(b.getDeriva_ORI()>0);
            jMotiuDerivacioORI.setText(b.getMotiuDerivacioORI());
            jObservacions.setText(b.getObservacions());
 
          //  jNExpDisciplina.setValue(b.getNExpDisciplina());
            jSancions.setText(b.getSancions());

            String prog = b.getProgrames();
            ArrayList<String> programes = StringUtils.parseStringToArray(prog, ";", StringUtils.CASE_INSENSITIVE);
            modelList1.clear();
            for(int i=0; i<programes.size(); i++)
            {
                modelList1.addElement(programes.get(i));
            }
           

            jCreador.setText(b.getDataCreacio());
            jModificat.setText(b.getModificat());
            jDataModificacio.setText(b.getDataModificacio());


            if(cfg.getCoreCfg().getUserInfo().getGrant()!=User.ADMIN)
            {
                //if(!jProfessor.getText().equals("")) jProfessor.setEditable(false);
                //System.out.println(jEstudis.getSelectedIndex()+", "+ (String)jEstudis.getSelectedItem());
                if(jEstudis.getSelectedIndex()>=0) {
                    jEstudis.setEnabled(false);
                }
                if(jGrup.getSelectedIndex()>=0) {
                    jGrup.setEnabled(false);
                }
                if(jEnsenyament.getSelectedIndex()>=0) {
                    jEnsenyament.setEnabled(false);
                }
            }

            //fill Table
            while(jTable1.getRowCount()>0)
            {
                modelTable1.removeRow(0);
            }
            
            for(String ky: bean.getImportacioSGD().keySet())
            {
                SgdInc sgdinc = bean.getImportacioSGD().get(ky);
                modelTable1.addRow(new Object[]{ky, sgdinc.getN1a(),sgdinc.getN2a(), sgdinc.getN3a() });
            }
            
    }

    public void deleteFromDB()
    {
        bean.deleteFromDB();
    }

//    public boolean isChanged()
//    {
//
//        //Let's start doing comparisions between sensible fields
//
//        BeanFitxaCurs bean2 = getData();
//        nchanges = BeanFitxaCurs.getChanges(bean, bean2);
//        //System.out.println("s'han profuit "+nchanges);
//        return nchanges==0;
//    }
//

     public BeanFitxaCurs getData()
     {
        BeanFitxaCurs b = new BeanFitxaCurs(cfg.getCoreCfg().getIesClient());

        b.setProfessor(jProfessor.getText());
        b.setGrup( (String) jGrup.getSelectedItem());
        b.setCurs( (String) jEstudis.getSelectedItem());
        b.setNivell( (String) jEnsenyament.getSelectedItem());
        b.setAny_academic(jAny_academic.getText());
        String aux = jNotaMitjanaFinal.getText();
        aux = aux.replaceAll(",", ".");
        float result = 0;
        try{
            result = (float) Double.parseDouble(aux);
        }
        catch(java.lang.NumberFormatException ex)
        {
            result = (float)  bean.getNotaMitjanaFinal();
        }
        b.setNotaMitjanaFinal(result);
        b.setDeriva_ORI(jDerivaORI.isSelected()? 1 : 0);
        b.setMotiuDerivacioORI(jMotiuDerivacioORI.getText());
        b.setObservacions(jObservacions.getText());
        b.setNumMateriesSuspesesJuny(jNumMateriesSuspesesJuny.getValue());
        b.setDataCreacio(jCreador.getText());

        int ncanvis = BeanFitxaCurs.getChanges(bean, b);
        
        if(isEditable && ncanvis>0)
        {
            String abrev =cfg.getCoreCfg().getUserInfo().getAbrev();
            String str;
            if(!abrev.equals("ADMIN") && !abrev.equals("GUARD")) {
                str = cfg.abrev2prof.get(abrev);
            }
            else {
                str = abrev;
            }
            b.setModificat(StringUtils.noNull(str));
            DataCtrl cd = new DataCtrl();
            b.setDataModificacio( cd.getDataSQL()+ " "+ cd.getHora());
        }

        String prog = "";
        for(int i=0; i<modelList1.getSize(); i++)
        {
            prog += modelList1.getElementAt(i) + ";";
        }
        prog = StringUtils.BeforeLast(prog, ";");

        b.setProgrames(prog);
        b.setSancions(jSancions.getText());

        return b;
      }


    public void setEditable(boolean editable, Profile profile) {


          boolean visible = true;
          String fullAnyAcademic = cfg.anyAcademicFitxes+"-"+(cfg.anyAcademicFitxes+1);
          if(bean.getAny_academic().equals(fullAnyAcademic))
          {            
                visible = FitxesGUI.moduleGrant.isGranted("fitxaActual_view", profile);
                
           }
           else
           {
               visible = FitxesGUI.moduleGrant.isGranted("fitxaAnterior_view", profile);
          }

                jPanel7.setVisible(!visible);
                jPanel8.setVisible(visible);
                jPanel6.setVisible(visible);


                jProfessor.setEditable(editable);


                //!alerta
                //jEstudis.setEnabled(editable);
                //jGrup.setEditable(editable);
                //jEnsenyament.setEditable(editable);

                //Editable 2:: per aquells camps que són importarts de l'SGD
                boolean editable2 = editable && FitxesGUI.moduleGrant.isGranted("imported_edit", profile);
                      

                if(editable2) {
                    toolTip_imported = "";
                }
                else {
                    toolTip_imported = "Aquestes dades s'importen automàticament";
                }

                jNotaMitjanaFinal.setEditable(editable);
                jNumMateriesSuspesesJuny.setEnabled(editable);
                jDerivaORI.setEnabled(editable);
                jMotiuDerivacioORI.setEditable(editable);
                jObservacions.setEditable(editable);
                jSancions.setEditable(editable);
                jList1.setEnabled(editable);
                jComboBox1.setEnabled(editable);
                jButton1.setEnabled(editable);

                isEditable = editable;
                
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAny_academic;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jCreador;
    private javax.swing.JLabel jDataModificacio;
    private javax.swing.JCheckBox jDerivaORI;
    private javax.swing.JComboBox jEnsenyament;
    private javax.swing.JComboBox jEstudis;
    private javax.swing.JComboBox jGrup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JLabel jModificat;
    private javax.swing.JTextArea jMotiuDerivacioORI;
    private javax.swing.JTextField jNotaMitjanaFinal;
    private com.toedter.components.JSpinField jNumMateriesSuspesesJuny;
    private javax.swing.JTextArea jObservacions;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jProfessor;
    private javax.swing.JTextArea jSancions;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
   
}

