/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormDadesPersonals.java
 *
 * Created on 07-abr-2011, 17:46:20
 */

package org.iesapp.modules.fitxes.forms;


import java.awt.Color;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URISyntaxException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import org.iesapp.clients.iesdigital.fitxes.BeanDadesPersonals;
import org.iesapp.clients.iesdigital.fitxes.PareTutor;
import org.iesapp.framework.data.User;
import org.iesapp.framework.pluggable.grantsystem.Profile;
import org.iesapp.framework.table.CellTableState;
import org.iesapp.framework.table.MyIconLabelRenderer;
import org.iesapp.framework.table.TextAreaEditor;
import org.iesapp.framework.table.TextAreaRenderer;
import org.iesapp.framework.util.CoreCfg;
import org.iesapp.framework.util.IconUtils;
import org.iesapp.modules.fitxes.FitxesGUI;
import org.iesapp.modules.fitxes.dialogs.AccionsAlumne4;
import org.iesapp.modules.fitxes.reports.ReportingClass;
import org.iesapp.modules.fitxescore.util.Cfg;
import org.iesapp.util.StringUtils;

/**
 *
 * @author Josep
 */
public class FormDadesPersonals extends javax.swing.JPanel {
    private DefaultTableModel modelTable1;
    private DefaultTableModel modelTable2;
    private DefaultTableModel modelTable3;
    private BeanDadesPersonals bean;
    private boolean isListening = false;
    private final FitxesGUI parental;
    private Profile profile;
    private boolean canEditMedicament;
    private Cfg cfg;
  
    /** Creates new form FormDadesPersonals */
    public FormDadesPersonals(FitxesGUI parent) {
        initComponents();
        this.parental = parent;
       
        jTable1.setIntercellSpacing( new java.awt.Dimension(2,2) );
        jTable1.setGridColor(java.awt.Color.gray);
        jTable1.setShowGrid(true);
        
        jTable2.setIntercellSpacing( new java.awt.Dimension(2,2) );
        jTable2.setGridColor(java.awt.Color.gray);
        jTable2.setShowGrid(true);
        
        jTable3.setIntercellSpacing( new java.awt.Dimension(2,2) );
        jTable3.setGridColor(java.awt.Color.gray);
        jTable3.setShowGrid(true);
        
        jTable3.getModel().addTableModelListener( new TableModelListener()
              {
           
                  @Override
              public void tableChanged(TableModelEvent e)
               {

                    int mrow = e.getFirstRow();
                    int mcol = e.getColumn();
                    if(isListening)
                    {
                        commitToDB(mrow);
                   }
              }
      });

       buttonGroup1.add(jRadioButton1);
       buttonGroup1.add(jRadioButton2);
        
      
       jTextArea1.getDocument().addDocumentListener(new DocumentListener() {

           @Override
            public void insertUpdate(DocumentEvent e) {
                updateComentaris();
            }

           @Override
            public void removeUpdate(DocumentEvent e) {
                updateComentaris();
            }

           @Override
            public void changedUpdate(DocumentEvent e) {
               updateComentaris();
            }

         
        });

    }
    
    public void startUp(boolean pertany)
    {
         //Labels
        if(!pertany)  //only admin can modify personal data
        {
            jSgdUser.setText("********");
            jSgdPwd.setText("********");
        }

    }
    
     private void updateComentaris() {
         String SQL1 = "UPDATE `"+CoreCfg.core_mysqlDBPrefix+"`.sig_medicaments_observ SET observacions=? WHERE exp2='"+bean.getExpedient()+"'";
         int nup = cfg.getCoreCfg().getMysql().preparedUpdate(SQL1, new Object[]{jTextArea1.getText()});
         if(nup<=0)
         {
              SQL1 = "INSERT INTO `"+CoreCfg.core_mysqlDBPrefix+"`.sig_medicaments_observ SET observacions=?, exp2='"+bean.getExpedient()+"'";
              cfg.getCoreCfg().getMysql().preparedUpdate(SQL1, new Object[]{jTextArea1.getText()});
         }
             
     }

  


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel()
        {
            public void paintComponent(Graphics g)
            {
                java.awt.Dimension d = getSize();
                ImageIcon img = new javax.swing.ImageIcon(getClass().getResource("/iesapp/modules/fitxes/icons/fons3.gif"));
                //Dimension size = new Dimension(img.getWidth(null), img.getHeight(null));
                //setPreferredSize(size);
                //setMinimumSize(size);
                //setMaximumSize(size);
                //setSize(size);
                //setLayout(null);
                for( int x = 0; x < d.width; x += img.getIconWidth() )
                for( int y = 0; y < d.height; y += img.getIconHeight() )
                g.drawImage( img.getImage(), x, y, null, null );
            }
        }
        ;
        jPanel1 = new javax.swing.JPanel();
        jNom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLlinatge1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLlinatge2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDNI = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jNRep = new javax.swing.JSpinner();
        jAnee = new javax.swing.JCheckBox();
        jRepe = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jEdat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jDataNaixement = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jNacionalitat = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPaisNaixement = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jProvinciaNaixement = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLocalitatNaixement = new javax.swing.JTextField();
        jSexe = new javax.swing.JComboBox();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jNexp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSgdUser = new javax.swing.JLabel();
        jSgdPwd = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jAdreca = new javax.swing.JTextField();
        jMunicipi = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLocalitat = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jCP = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLinkButton1 = new com.l2fprod.common.swing.JLinkButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jPanel7.setName("jPanel7"); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iesapp/modules/fitxes/icons/halt.gif"))); // NOI18N
        jLabel23.setText("  No té permisos per veure el contingut");
        jLabel23.setName("jLabel23"); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(180, 180, 180))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addContainerGap())
        );

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel6.setName("jPanel6"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dades generals"));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setOpaque(false);

        jNom.setName("jNom"); // NOI18N

        jLabel3.setText("Nom");
        jLabel3.setName("jLabel3"); // NOI18N

        jLlinatge1.setName("jLlinatge1"); // NOI18N

        jLabel4.setText("Llinatge1");
        jLabel4.setName("jLabel4"); // NOI18N

        jLlinatge2.setName("jLlinatge2"); // NOI18N

        jLabel5.setText("Llinatge2");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel9.setText("DNI");
        jLabel9.setName("jLabel9"); // NOI18N

        jDNI.setName("jDNI"); // NOI18N

        jLabel21.setText("Núm. Repeticions");
        jLabel21.setName("jLabel21"); // NOI18N

        jNRep.setName("jNRep"); // NOI18N

        jAnee.setText("NESE");
        jAnee.setEnabled(false);
        jAnee.setName("jAnee"); // NOI18N
        jAnee.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jAneeStateChanged(evt);
            }
        });
        jAnee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAneeActionPerformed(evt);
            }
        });

        jRepe.setText("REPETEIX AQUEST CURS");
        jRepe.setName("jRepe"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLlinatge1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                    .addComponent(jLabel21)
                    .addComponent(jNRep, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLlinatge2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jNom, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRepe)
                        .addGap(18, 18, 18)
                        .addComponent(jAnee)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLlinatge1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLlinatge2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jNRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAnee)
                            .addComponent(jRepe))
                        .addContainerGap())))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dades de naixement"));
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setOpaque(false);

        jEdat.setName("jEdat"); // NOI18N

        jLabel6.setText("Edat");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel10.setText("Data naixement");
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setText("Sexe");
        jLabel11.setName("jLabel11"); // NOI18N

        jDataNaixement.setName("jDataNaixement"); // NOI18N

        jLabel12.setText("Nacionalitat");
        jLabel12.setName("jLabel12"); // NOI18N

        jNacionalitat.setName("jNacionalitat"); // NOI18N

        jLabel13.setText("Pais de naixement");
        jLabel13.setName("jLabel13"); // NOI18N

        jPaisNaixement.setName("jPaisNaixement"); // NOI18N

        jLabel14.setText("Provincia");
        jLabel14.setName("jLabel14"); // NOI18N

        jProvinciaNaixement.setName("jProvinciaNaixement"); // NOI18N

        jLabel15.setText("Municipi");
        jLabel15.setName("jLabel15"); // NOI18N

        jLocalitatNaixement.setName("jLocalitatNaixement"); // NOI18N

        jSexe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Home", "Dona", "" }));
        jSexe.setName("jSexe"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDataNaixement, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(jPaisNaixement)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jEdat, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSexe, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel11)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jNacionalitat, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProvinciaNaixement, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLocalitatNaixement)
                            .addComponent(jLabel15))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jEdat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jNacionalitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDataNaixement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPaisNaixement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jProvinciaNaixement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLocalitatNaixement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel10.setName("jPanel10"); // NOI18N

        jLabel1.setText("N. Expedient");
        jLabel1.setName("jLabel1"); // NOI18N

        jNexp.setText("...");
        jNexp.setName("jNexp"); // NOI18N

        jLabel2.setText("usuariSGDWeb:");
        jLabel2.setName("jLabel2"); // NOI18N

        jSgdUser.setBackground(new java.awt.Color(255, 255, 204));
        jSgdUser.setText("···");
        jSgdUser.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jSgdUser.setName("jSgdUser"); // NOI18N
        jSgdUser.setOpaque(true);

        jSgdPwd.setBackground(new java.awt.Color(255, 255, 204));
        jSgdPwd.setText("···");
        jSgdPwd.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jSgdPwd.setName("jSgdPwd"); // NOI18N
        jSgdPwd.setOpaque(true);

        jLabel20.setText("passwordSGD:");
        jLabel20.setName("jLabel20"); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNexp)
                .addGap(128, 128, 128)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSgdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSgdPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jNexp)
                    .addComponent(jLabel2)
                    .addComponent(jSgdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jSgdPwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel11.setName("jPanel11"); // NOI18N
        jPanel11.setOpaque(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Adreça familiar"));
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setOpaque(false);

        jLabel16.setText("Adreça");
        jLabel16.setName("jLabel16"); // NOI18N

        jAdreca.setName("jAdreca"); // NOI18N

        jMunicipi.setName("jMunicipi"); // NOI18N

        jLabel17.setText("Municipi");
        jLabel17.setName("jLabel17"); // NOI18N

        jLabel18.setText("Localitat");
        jLabel18.setName("jLabel18"); // NOI18N

        jLocalitat.setName("jLocalitat"); // NOI18N

        jLabel19.setText("CP");
        jLabel19.setName("jLabel19"); // NOI18N

        jCP.setName("jCP"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jAdreca, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jMunicipi, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLocalitat, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCP, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jAdreca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jMunicipi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLocalitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefons"));
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setOpaque(false);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        modelTable1 = new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Telèfons"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        jTable1.setModel(modelTable1);
        jTable1.setName("jTable1"); // NOI18N
        jTable1.setRowHeight(32);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Informació tutors"));
        jPanel5.setInheritsPopupMenu(true);
        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setOpaque(false);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        modelTable2 = new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Parentesc", "Nom Tutor", "Telefons", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        jTable2.setModel(modelTable2);
        jTable2.setRowHeight(32);
        jTable2.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable2.getColumnModel().getColumn(2).setCellRenderer(new TextAreaRenderer());
        jTable2.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTable2.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTable2.setName("jTable2"); // NOI18N
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
        );

        jPanel9.setName("jPanel9"); // NOI18N
        jPanel9.setOpaque(false);

        jLabel7.setText("* Per a més informació, consultau l'adreça:");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText("* Aquestes dades només les pot modificar l'administrador. Si detectau alguna errada comunicau-la a prefectura");
        jLabel8.setName("jLabel8"); // NOI18N

        jLinkButton1.setForeground(new java.awt.Color(0, 0, 204));
        jLinkButton1.setText("https://www3.caib.es/xestib/");
        jLinkButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLinkButton1.setName("jLinkButton1"); // NOI18N
        jLinkButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLinkButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLinkButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLinkButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 732, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Dades  Personals", jPanel6);

        jPanel8.setName("jPanel8"); // NOI18N

        jLabel24.setText("Medicaments");
        jLabel24.setName("jLabel24"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setToolTipText("");
        jList1.setName("jList1"); // NOI18N
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList1);

        jLabel25.setText("Historial de subministraments");
        jLabel25.setName("jLabel25"); // NOI18N

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        modelTable3 = new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "id", "Data", "Hora", "Medicament", "Autorització", "Observacions"
            }
        ){
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, canEditMedicament
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        jTable3.setModel(modelTable3);
        Icon[] icons = new Icon[]{IconUtils.getDeleteIcon()};

        jTable3.getColumnModel().getColumn(0).setCellRenderer(new MyIconLabelRenderer(icons));
        jTable3.getColumnModel().getColumn(5).setCellEditor(new TextAreaEditor());
        jTable3.getColumnModel().getColumn(5).setCellRenderer(new TextAreaRenderer());
        jTable3.getColumnModel().getColumn(5).setPreferredWidth(200);
        jTable3.setRowHeight(32);
        jTable3.setName("jTable3"); // NOI18N
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable3);

        jPanel12.setName("jPanel12"); // NOI18N

        jRadioButton1.setText("Mode edició");
        jRadioButton1.setName("jRadioButton1"); // NOI18N
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Mode submistració");
        jRadioButton2.setName("jRadioButton2"); // NOI18N
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2))
        );

        jLabel26.setText("Observacions");
        jLabel26.setName("jLabel26"); // NOI18N

        jScrollPane5.setName("jScrollPane5"); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane5.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel24)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                .addComponent(jLabel26))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jScrollPane5)
                            .addGap(10, 10, 10)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                    .addComponent(jLabel25))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(393, 393, 393))
        );

        jTabbedPane1.addTab("Dades Mèdiques", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jTabbedPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLinkButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLinkButton1ActionPerformed
           
             String url = jLinkButton1.getText();
            try {
            try {
                Desktop.getDesktop().browse(new java.net.URI(url));
            } catch (IOException ex) {
                Logger.getLogger(FormDadesPersonals.class.getName()).log(Level.SEVERE, null, ex);
            }
            } catch (URISyntaxException ex) {
                Logger.getLogger(FormDadesPersonals.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jLinkButton1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        
        if(!canEditMedicament){
            return;
        }
        
        int nsel = jList1.getSelectedIndex();
         
        int idMedicament = bean.getListMedicaments().get(nsel).getId(); 
        
        if(nsel>=0 && evt.getClickCount()==2 && evt.getButton()==MouseEvent.BUTTON1)
        {
            //Mode administracio
            if(jRadioButton2.isSelected())
            {
           
            if(!bean.getListMedicaments().get(nsel).isAutoritzat()) {
                    return;
                }
            
            //inclou i fillTable()
            String SQL1 = "INSERT INTO sig_medicaments_reg (exp2,data,idAutoritzat,idMedicament) "
                    + " VALUES('"+bean.getExpedient()+"',NOW(),'"+cfg.getCoreCfg().getUserInfo().getAbrev()+"','"+idMedicament+"')";
            int nup = cfg.getCoreCfg().getMysql().executeUpdate(SQL1);
            fillTable();
            }
            
            //Mode edicio
            if(jRadioButton1.isSelected())
            {
                //Toogle d'autoritzat a no autoritzat i viceversa
                boolean enabled = ((JLabel) jList1.getSelectedValue()).isEnabled();
                if(enabled)
                {
                     String SQL1 = "DELETE FROM `"+CoreCfg.core_mysqlDBPrefix+"`.sig_medicaments_alumnes WHERE exp2="+bean.getExpedient()+" AND idMedicament="+idMedicament;
                     int nup = cfg.getCoreCfg().getMysql().executeUpdate(SQL1);
                }
                else
                {
                     String SQL1 = "INSERT INTO `"+CoreCfg.core_mysqlDBPrefix+"`.sig_medicaments_alumnes (exp2,idMedicament) VALUES('"+bean.getExpedient()+"','"+idMedicament+"')";
                     int nup = cfg.getCoreCfg().getMysql().executeUpdate(SQL1);
                }
                
                //Torna a carregar el bean de dadespersonals
                int exp2 = bean.getExpedient();
                bean.getFromDB(exp2, cfg.anyAcademicFitxes);
                createMedicamentList();
            }
            
        }
        
    }//GEN-LAST:event_jList1MouseClicked

    //Prepara l'informe
    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked

        if(!FitxesGUI.moduleGrant.isGranted("medicaments_give", profile)){
            return;
        }
        
        int row = jTable3.getSelectedRow();
        int col = jTable3.getSelectedColumn();
        if(row>=0)
        {
            if(col==0)
            {
                 //Esborra                
                Object[] options = {"No","Sí"};

                int n = JOptionPane.showOptionDialog(null,
                "Segur que voleu esborrar aquesta entrada?", "Confirmació",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.YES_NO_OPTION,
                null,
                options,
                options[0]);

                if(n!=1) {
                    return;
                }
                int id = ((CellTableState) jTable3.getValueAt(row, 0)).getCode();
                String SQL1 = "DELETE FROM sig_medicaments_reg WHERE id="+id;
                int nup = cfg.getCoreCfg().getMysql().executeUpdate(SQL1);
                fillTable();
                
            }
            if(col>0 && col<5 && evt.getClickCount()==2)
            {
                //Genera autoritzacio
                HashMap map = new HashMap();
                map.put("nomAlumne", bean.getLlinatge1()+" "+bean.getLlinatge2()+", "+bean.getNom1());
                map.put("grup", bean.getEstudis()+" "+bean.getGrupLletra());
                map.put("edat", ""+bean.getEdat());
                map.put("dia", (String) jTable3.getValueAt(row, 1));
                map.put("hora", (String) jTable3.getValueAt(row, 2));
                map.put("medicament", (String) jTable3.getValueAt(row, 3));
                map.put("autoritza", (String) jTable3.getValueAt(row, 4));
                map.put("observacions", StringUtils.noNull((String) jTable3.getValueAt(row, 5)));
                map.put("foto", bean.getPhoto());
                map.put("guardia", "");
                
                ReportingClass rc = new ReportingClass(cfg);
                rc.customReport(null, map, "misc/autoritzacio_medicament");
            }
        }
    }//GEN-LAST:event_jTable3MouseClicked

    private void jAneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAneeActionPerformed
        boolean amiadmin = cfg.getCoreCfg().getUserInfo().getGrant()==User.ADMIN;
        if(!(amiadmin || FitxesGUI.moduleGrant.isGranted("nese_edit", profile)) ){
            return;
        }
        
        if(jAnee.isSelected())
        {
            
            Object[] possibilities = null;
            String s = (String)JOptionPane.showInputDialog(
                    null,
                    "Tipus de NESE:",
                    "Formulari",
                    JOptionPane.PLAIN_MESSAGE,
                    null,
                    possibilities,
                    "");

            //If a string was returned, say so.
            if ((s != null) && (s.trim().length() > 0)) {
                String SQL1 ="UPDATE `"+CoreCfg.core_mysqlDBPrefix+"`.alumne SET anee=? WHERE exp2="+bean.getExpedient();
                int nup = cfg.getCoreCfg().getMysql().preparedUpdate(SQL1, new Object[]{s});
                //Crea la pestanya anee
                FormNESE formNese = new FormNESE(parental);
                bean.setNese(s);
                formNese.setDadesPersonals(bean, cfg);
                jTabbedPane1.addTab("NESE", formNese);
                jTabbedPane1.setSelectedIndex(2);
            }
            else
            {
                jAnee.setSelected(false);
            }
        }
        else
        {
            Object[] options = {"No","Sí"};

            int n = JOptionPane.showOptionDialog(null,
            "Voleu descatalogar aquest alumne com NESE?", "Confirmació",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            options,
            options[0]);

            if(n==1)
            {
                String SQL1 ="UPDATE `"+CoreCfg.core_mysqlDBPrefix+"`.xes_alumne SET anee='' WHERE exp2="+bean.getExpedient();
                int nup = cfg.getCoreCfg().getMysql().executeUpdate(SQL1);
                
                //Esborra la pestanya anee
                if(jTabbedPane1.getTabCount()>2) {
                    jTabbedPane1.remove(2);
                }
            }
            else
            {
                jAnee.setSelected(true);
            }
        }
    }//GEN-LAST:event_jAneeActionPerformed

    private void jAneeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jAneeStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jAneeStateChanged

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        colorify();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        colorify();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    public void colorify()
    {
        if(jRadioButton1.isSelected())
        {
            jList1.setBackground(Color.red);
            jList1.setOpaque(true);
            jTextArea1.setEditable(true);
        }
        else
        {
            jList1.setBackground(Color.WHITE);
            jList1.setOpaque(true);
            jTextArea1.setEditable(false);
        }
    }
    

//    private void mostraImatge(String path, java.awt.Point org, java.awt.Dimension size)
//    {
//        Image img = Toolkit.getDefaultToolkit().getImage(path);
//        int width = img.getWidth(null);
//        int height = img.getHeight(null);
//        double ratio = width/(1.0*height);
//        int heigth2 = 150;
//        int width2 = (int) ratio*heigth2;
//        Image image = createImage(new FilteredImageSource(img.getSource(),
//                     new CropImageFilter(org.x,org.y,size.width,size.height))); //inici,inici i amplada,amplada
//        Image scaledInstance = image.getScaledInstance(-1, heigth2, Image.SCALE_DEFAULT);
//
//        jPhoto.setIcon( new ImageIcon(scaledInstance) ); // NOI18N
//    }
//
//    private void mostraImatge(byte[] foto)
//    {
//        int heigth2 = jPhoto.getHeight();
//        Image image = Toolkit.getDefaultToolkit().createImage(foto);
//        Image scaledInstance = image.getScaledInstance(-1, heigth2, Image.SCALE_SMOOTH);
//
//        jPhoto.setIcon( new ImageIcon(scaledInstance) ); // NOI18N
//    }

    public void setData(BeanDadesPersonals bean, Cfg cfg)
    {
        this.cfg = cfg;
        this.bean = bean;
        profile = AccionsAlumne4.createProfileFromDP(bean);
        canEditMedicament = FitxesGUI.moduleGrant.isGranted("medicaments_edit", profile);
        
        applyGrantToUI();
        
        jNom.setText(bean.getNom1());
        jLlinatge1.setText(bean.getLlinatge1());
        jLlinatge2.setText(bean.getLlinatge2());
        jEdat.setText( "" + bean.getEdat());
//        byte[] photo = bean.getFoto();
//        if(photo!=null)
//        {
//            //make sure you rescale the photo to the suitable size
//            mostraImatge(photo);
//        }
//        else
//        {
//            if(bean.getSexe().contains("H"))
//            {
//                jSexe.setSelectedIndex(0);
//               // jPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/iesapp/modules/fitxes/icons/default.gif")));
//            }
//            else if(bean.getSexe().contains("D"))
//            {
//                jSexe.setSelectedIndex(1);
//                //jPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/iesapp/modules/fitxes/icons/default2.gif")));
//            }
//            else
//            {
//                jSexe.setSelectedIndex(2);
//                //jPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/iesapp/modules/fitxes/icons/default.gif")));
//            }
//        }

          if(bean.getSexe().contains("H"))
            {
                jSexe.setSelectedIndex(0);

            }
            else if(bean.getSexe().contains("D"))
            {
                jSexe.setSelectedIndex(1);

            }
            else
            {
                jSexe.setSelectedIndex(2);
            }

        jDataNaixement.setDate(bean.getDataNaixament());
        jNacionalitat.setText(bean.getNacionalitat());
        jPaisNaixement.setText(bean.getPaisNaixament());
        jProvinciaNaixement.setText(bean.getProvinciaNaixament());
        jLocalitatNaixement.setText(bean.getLocalitatNaixament());
        jDNI.setText(bean.getDni());
        jAdreca.setText(bean.getAdreca());
        jMunicipi.setText(bean.getMunicipi());
        jLocalitat.setText(bean.getLocalitat());
        jCP.setText(bean.getCp());
        jNexp.setText(""+bean.getExpedient());
        jNRep.setValue(bean.getNumRep());

        jSgdUser.setText(bean.getSgdUser());
        jSgdPwd.setText(bean.getSgdPasswd());
        jAnee.setSelected(bean.isAnee());
        jAnee.setEnabled(false);
        jRepe.setSelected(bean.isRepetidor());
        jRepe.setEnabled(bean.isRepetidorEditable());


        while(jTable1.getRowCount()>0) {
            modelTable1.removeRow(0);
        }

        ArrayList<String> turg = bean.getTelefonsUrgencia();
        for(int i=0; i<turg.size(); i++) {
            modelTable1.addRow(new Object[]{turg.get(i)});
        }

        while(jTable2.getRowCount()>0) {
            modelTable2.removeRow(0);
        }

        ArrayList<PareTutor> pt = bean.getTutorsInfo();
        for(int i=0; i<pt.size(); i++)
        {
            PareTutor item = pt.get(i);
//            modelTable2.addRow(new Object[]{
//                item.getParentesc(), item.getNom(), item.getTelefons(),
//                item.getProfessio(), item.getEdat(), item.getEmails()
//            });
            modelTable2.addRow(new Object[]{
                item.getParentesc(), item.getNom(), item.getTelefons(),
                item.getEmails()
            });
        }


        createMedicamentList();
       
        fillTable();
        
        if(FitxesGUI.moduleGrant.isGranted("nese_view", profile))
        {
            if(jTabbedPane1.getTabCount()>2) {
                jTabbedPane1.remove(2);
            }
            //If nese must display a new tab
            if(bean.isAnee())
            {
                FormNESE formNese = new FormNESE(parental);
                formNese.setDadesPersonals(bean, cfg);
                jTabbedPane1.addTab("NESE", formNese);
            }
        }
    }

     public BeanDadesPersonals getData()
     {
        BeanDadesPersonals b = new BeanDadesPersonals(cfg.getCoreCfg().getIesClient());

        b.setNom1(jNom.getText());
        b.setLlinatge1(jLlinatge1.getText());
        b.setLlinatge2(jLlinatge2.getText());
        b.setEdat( (int) Double.parseDouble(jEdat.getText()));
        String aux = (String) jSexe.getSelectedItem();
        String sex = " ";
        if(aux.contains("H")) {
            sex = "H";
        }
        else if(aux.contains("D")) {
            sex = "D";
        }
        b.setSexe(sex);

        b.setDataNaixament(new java.sql.Date(jDataNaixement.getDate().getTime()));
        b.setNacionalitat(jNacionalitat.getText());
        b.setPaisNaixament(jPaisNaixement.getText());
        b.setProvinciaNaixament(jProvinciaNaixement.getText());
        b.setLocalitatNaixament(jLocalitatNaixement.getText());
        b.setDni(jDNI.getText());
        //b.setTargetaSanitaria(jTargetaSanitaria.getText());
        b.setAdreca(jAdreca.getText());
        b.setMunicipi(jMunicipi.getText());
        b.setLocalitat(jLocalitat.getText());
        b.setCp(jCP.getText());
        b.setNumRep(((Number) jNRep.getValue()).intValue());
        b.setAnee(jAnee.isSelected());
        b.setRepetidor(jRepe.isSelected());

//        b.setFoto(Utils.createByteArray( jPhoto.getIcon() ));



        return b;
      }

      public void setEditable(boolean editable, boolean pertany) {
      
            boolean visible = FitxesGUI.moduleGrant.isGranted("dadesPersonals_view", profile);
            boolean amiadmin = cfg.getCoreCfg().getUserInfo().getGrant()==User.ADMIN;
            
            jPanel7.setVisible(!visible);           
            jTabbedPane1.setVisible(visible);
         
            jNom.setEditable(editable);
            jLlinatge1.setEditable(editable);
            jLlinatge2.setEditable(editable);
            jEdat.setEditable(editable);
            jSexe.setEditable(editable);
            jSexe.setEnabled(editable);
            jDNI.setEditable(editable);
            jNRep.setEnabled(editable);
            jDataNaixement.setEnabled(editable);
            jNacionalitat.setEditable(editable);
            jPaisNaixement.setEditable(editable);
            jProvinciaNaixement.setEditable(editable);
            jLocalitatNaixement.setEditable(editable);
            jAdreca.setEditable(editable);
            jMunicipi.setEditable(editable);
            jLocalitat.setEditable(editable);
            jCP.setEditable(editable);
            jTable1.setEnabled(editable);
            jTable2.setEnabled(editable);
            //jAnee.setEnabled(editable);
             if (!jAnee.isSelected() && !jAnee.isEnabled()) {
                  jAnee.setVisible(FitxesGUI.moduleGrant.isGranted("nese_edit", profile));
            } else {
                  jAnee.setVisible(true);
             }
            
            jAnee.setEnabled(FitxesGUI.moduleGrant.isGranted("nese_edit", profile));
            
            jRepe.setEnabled(editable && bean.isRepetidorEditable());
            jRepe.setVisible(jRepe.isSelected() || amiadmin);
    }


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField jAdreca;
    private javax.swing.JCheckBox jAnee;
    private javax.swing.JTextField jCP;
    private javax.swing.JTextField jDNI;
    private com.toedter.calendar.JDateChooser jDataNaixement;
    private javax.swing.JTextField jEdat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.l2fprod.common.swing.JLinkButton jLinkButton1;
    private javax.swing.JList jList1;
    private javax.swing.JTextField jLlinatge1;
    private javax.swing.JTextField jLlinatge2;
    private javax.swing.JTextField jLocalitat;
    private javax.swing.JTextField jLocalitatNaixement;
    private javax.swing.JTextField jMunicipi;
    private javax.swing.JSpinner jNRep;
    private javax.swing.JTextField jNacionalitat;
    private javax.swing.JLabel jNexp;
    private javax.swing.JTextField jNom;
    private javax.swing.JTextField jPaisNaixement;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jProvinciaNaixement;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JCheckBox jRepe;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JComboBox jSexe;
    private javax.swing.JLabel jSgdPwd;
    private javax.swing.JLabel jSgdUser;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    private void fillTable() {
         isListening = false;
        //erase table
        while(jTable3.getRowCount()>0) {
            modelTable3.removeRow(0);
        }
        
        //retrieve from db
        String SQL1 = "SELECT "
                + " reg.id, "
                + " DATE_FORMAT(reg.DATA, '%d-%m-%Y') AS dia,"
                + " DATE_FORMAT(reg.DATA, '%H:%i:%s') AS hora,"
                + " reg.idAutoritzat, "
                + " IF(reg.idAutoritzat='PREF','PREFECTURA', IF(reg.idAutoritzat='ADMIN', 'ADMINISTRADOR', "
                + " IF(reg.idAutoritzat='GUARD', 'PROFESSOR DE GUARDIA',prof.nombre))) AS autoritzatper, "
                + " med.descripcio, "
                + " reg.observacions "
                + " FROM "
                + " sig_medicaments_reg AS reg  "
                + " INNER JOIN  `"+CoreCfg.core_mysqlDBPrefix+"`.sig_medicaments AS med  "
                + " ON med.id = reg.idMedicament  "
                + " LEFT JOIN "
                + " sig_professorat AS prof "
                + " ON prof.abrev=reg.idAutoritzat "
                + " WHERE exp2 = " + bean.getExpedient()+ ""
                + " ORDER by reg.data";
        
         try {
            Statement st = cfg.getCoreCfg().getMysql().createStatement();
            ResultSet rs1 = cfg.getCoreCfg().getMysql().getResultSet(SQL1,st);
              
            while(rs1!=null && rs1.next())
            {
                
                CellTableState cts = new CellTableState("",rs1.getInt("id"),0);
                
                modelTable3.addRow(new Object[]{cts,rs1.getString("dia"), 
                    rs1.getString("hora"), rs1.getString("descripcio"),rs1.getString("autoritzatper"),
                rs1.getString("observacions")});
            }
            if(rs1!=null) {
                 rs1.close();
                 st.close();
             }
        } catch (SQLException ex) {
            Logger.getLogger(FormDadesPersonals.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         isListening = true;
        
    }
    
  private void commitToDB(int mrow) {
            //jTable3.editCellAt(0,0);
            int id = ((CellTableState) jTable3.getValueAt(mrow, 0)).getCode(); 
            String comment = (String) jTable3.getValueAt(mrow, 5); 
             //inclou i fillTable()
            String SQL1 = "UPDATE sig_medicaments_reg SET observacions=? WHERE id="+id;
            int nup = cfg.getCoreCfg().getMysql().preparedUpdate(SQL1, new Object[]{comment});
  }

    public void setSelectedIndex(int index) {
        jTabbedPane1.setSelectedIndex(index);
    }

    public int getSelectedIndex() { 
        return jTabbedPane1.getSelectedIndex();
    }

    private void createMedicamentList() {
        //Dades Mediques
        DefaultListModel modelList1 = new DefaultListModel();
        for(int i=0; i<bean.getListMedicaments().size(); i++)
        {
           javax.swing.JLabel jEtiqueta = new javax.swing.JLabel(bean.getListMedicaments().get(i).getDescripcio()); 
           jEtiqueta.setFont(new java.awt.Font("Tahoma", 1, 16));
           if(bean.getListMedicaments().get(i).isAutoritzat())
           {
               jEtiqueta.setIcon(new ImageIcon(getClass().getResource("/org/iesapp/modules/fitxes/icons/greenspot.gif")));
               jEtiqueta.setToolTipText("Doble-click per subministrar");
           }
           else
           {
               jEtiqueta.setIcon(new ImageIcon(getClass().getResource("/org/iesapp/modules/fitxes/icons/redspot.gif")));
               jEtiqueta.setEnabled(false);
               jEtiqueta.setToolTipText("No autoritzat");
           }
           
           modelList1.addElement( jEtiqueta );
           jTextArea1.setText(bean.getListMedicaments().get(i).getObservacions());
        }
        jList1.setModel(modelList1);
        jList1.setCellRenderer( new CustomCellRenderer() );
    }

    private void applyGrantToUI() {
       if(FitxesGUI.moduleGrant.isGranted("medicaments_edit", profile))        
       {
           if(cfg.getCoreCfg().getUserInfo().getGrant()==User.ADMIN)
           {
               jRadioButton1.setSelected(true);
           }
           else
           {
               jRadioButton2.setSelected(true);
           }
       }
       else
       {
           jRadioButton2.setSelected(true);
           jPanel12.setVisible(false);
       }
       
       jTabbedPane1.setEnabledAt(0, FitxesGUI.moduleGrant.isGranted("dadesPersonals_view", profile));
       jTabbedPane1.setEnabledAt(1, FitxesGUI.moduleGrant.isGranted("medicaments_view", profile));
    
    }

   private static class CustomCellRenderer implements ListCellRenderer {

        public CustomCellRenderer() {
        }
       
         public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
             
             JLabel label = (JLabel) value;
           
             
             if(isSelected)
             {
                 label.setOpaque(true);
                 DefaultListCellRenderer adaptee = new DefaultListCellRenderer();
                 label.setBackground(adaptee.getForeground());
             }
             else
             {  
                 label.setOpaque(false);
             }
             
             return (Component) label;
        }
    }
}


 
