/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.iesapp.modules.fitxes.dialogs;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import org.iesapp.framework.util.CoreCfg;
import org.iesapp.modules.fitxescore.util.Cfg;
import org.iesapp.util.StringUtils;

/**
 *
 * @author Josep
 */
public class AltesPanel extends javax.swing.JPanel {
    private final DefaultListModel modelList1;
    private final DefaultListModel modelList2;
    private Cfg cfg;

    /**
     * Creates new form AltesPanel
     */
    public AltesPanel() {
        initComponents();
        modelList1 = new DefaultListModel();
        jList1.setModel(modelList1);
        modelList2= new DefaultListModel();
        jList2.setModel(modelList2);            
    }

    public void startUp(Cfg cfg)
    {
        this.cfg = cfg;
       
        //Determina dates d'alta i nombre d'alumnes
        String SQL1 = "SELECT dataAlta, COUNT(exp2) as total FROM `"+CoreCfg.core_mysqlDBPrefix+"`.xes_alta GROUP BY dataAlta ORDER BY dataAlta DESC";
        
         try {
            Statement st = cfg.getCoreCfg().getMysql().createStatement();
            ResultSet rs1 = cfg.getCoreCfg().getMysql().getResultSet(SQL1,st);
            while(rs1!=null && rs1.next())
            {
               modelList1.addElement(rs1.getString("dataAlta")+" : "+rs1.getString("total")+ " alumnes");               
            }
            rs1.close();
            st.close();
        } catch (SQLException ex) {
            Logger.getLogger(AltesPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Relació de dates d'alta i alumnes"));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        int i=jList1.getSelectedIndex();
        if(i>=0)
        {
            String dataAlta = (String) jList1.getSelectedValue();
            dataAlta = StringUtils.BeforeLast(dataAlta, " :");
            
            modelList2.clear();
            //Carrega alumnes que han estat donats d'alta aquest dia
            String SQL1 = "SELECT CONCAT(llinatge1,' ',llinatge2,', ',nom1,' (',xh.Estudis,' ',xh.Grup,')') "+
                    " AS txt FROM `" + CoreCfg.core_mysqlDBPrefix + "`.xes_alumne AS xes INNER JOIN `" + 
                    CoreCfg.core_mysqlDBPrefix + "`.xes_alumne_historic AS xh "+
                    " ON xh.Exp2=xes.Exp2 AND xh.anyAcademic="+cfg.anyAcademicFitxes+" INNER JOIN `" + 
                    CoreCfg.core_mysqlDBPrefix + "`.xes_alta AS xal ON xal.Exp2=xh.Exp2 WHERE xal.dataAlta='"+
                    dataAlta+"' AND xh.AnyAcademic="+cfg.getCoreCfg().anyAcademic+
                    " ORDER BY txt";
                  
            //System.out.println(SQL1);
             try {
                Statement st = cfg.getCoreCfg().getMysql().createStatement();
                ResultSet rs1 = cfg.getCoreCfg().getMysql().getResultSet(SQL1,st);
                while (rs1 != null && rs1.next()) {
                    modelList2.addElement(rs1.getString(1));
                }
                rs1.close();
                st.close();
            } catch (SQLException ex) {
                Logger.getLogger(AltesPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jList1ValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
