/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Cleaner.java
 *
 * Created on 14-ene-2012, 17:17:19
 */
package org.iesapp.modules.fitxes.dialogs;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import org.iesapp.framework.table.MyCheckBoxRenderer;
import org.iesapp.framework.util.CoreCfg;
import org.iesapp.modules.fitxescore.util.Cfg;
import org.iesapp.util.StringUtils;

/**
 *
 * @author Josep
 */
public class Cleaner extends javax.swing.JDialog {
    private DefaultTableModel modelTable1;
    private final Cfg cfg;

    /** Creates new form Cleaner */
    public Cleaner(java.awt.Frame parent, boolean modal, Cfg cfg) {
        super(parent, modal);
        this.cfg = cfg;
        initComponents();
        
        refresh();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                boolean q = false;
                if(colIndex == 0)
                q = true;
                return q;
            }};
            jCheckBox1 = new javax.swing.JCheckBox();
            jLabel4 = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            setTitle("Netejador");
            setIconImage(null);

            jPanel2.setName("jPanel2"); // NOI18N
            jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 5));

            jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/iesapp/modules/fitxes/icons/exit.gif"))); // NOI18N
            jButton2.setText("Surt");
            jButton2.setName("jButton2"); // NOI18N
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });
            jPanel2.add(jButton2);

            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/iesapp/modules/fitxes/icons/refresh.gif"))); // NOI18N
            jButton1.setText("Refresca");
            jButton1.setName("jButton1"); // NOI18N
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });
            jPanel2.add(jButton1);

            jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/iesapp/modules/fitxes/icons/clean.gif"))); // NOI18N
            jButton3.setText("Corregir");
            jButton3.setName("jButton3"); // NOI18N
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });
            jPanel2.add(jButton3);

            jPanel3.setName("jPanel3"); // NOI18N

            jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jLabel1.setText("Actuacions que tenen com a càstig dies d'expulsió o de dimecres");
            jLabel1.setName("jLabel1"); // NOI18N

            jLabel3.setText("Pitjau el botó corregir per tal de tancar les seleccionades automàticament");
            jLabel3.setName("jLabel3"); // NOI18N

            jLabel2.setText("Sembla que les següents actuacions ja han duit a terme el càstig i per tant haurien d'estar tancades");
            jLabel2.setName("jLabel2"); // NOI18N

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addContainerGap(370, Short.MAX_VALUE))
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel3)
                    .addContainerGap())
            );

            jScrollPane1.setName("jScrollPane1"); // NOI18N

            modelTable1 = new javax.swing.table.DefaultTableModel(
                new Object [][] {
                },
                new String [] {
                    "Tria","id", "Grup", "Alumne/a", "Actuació", "Iniciada",
                    "Fi càstig"
                }
            );
            jTable1.setModel(modelTable1);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(250);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(250);
            JCheckBox checkbox = new JCheckBox("");
            checkbox.setHorizontalAlignment(SwingConstants.CENTER);
            jTable1.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor( checkbox ));
            jTable1.getColumnModel().getColumn(0).setCellRenderer(new MyCheckBoxRenderer());

            jTable1.getTableHeader().setReorderingAllowed(false);
            jTable1.setRowHeight(32);
            jTable1.setName("jTable1"); // NOI18N
            jScrollPane1.setViewportView(jTable1);

            jCheckBox1.setSelected(true);
            jCheckBox1.setText("Tots");
            jCheckBox1.setName("jCheckBox1"); // NOI18N
            jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jCheckBox1ActionPerformed(evt);
                }
            });

            jLabel4.setText("Cal que reviseu ...");
            jLabel4.setName("jLabel4"); // NOI18N

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jCheckBox1)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel4))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addGap(1, 1, 1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox1)
                        .addComponent(jLabel4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(1, 1, 1))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    //Refresh
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       refresh();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    //Corregeix
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        
        for(int i=0; i<jTable1.getRowCount(); i++)
        {
            boolean triat = (Boolean) jTable1.getValueAt(i, 0);
            int id = ((Number) jTable1.getValueAt(i, 1)).intValue();
            if(triat)
            {
                String SQL1 = "UPDATE tuta_reg_actuacions SET data2=CURRENT_DATE() WHERE id="+id;
                int nup = cfg.getCoreCfg().getMysql().executeUpdate(SQL1);
            }
        }
        
        refresh();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        boolean tots = jCheckBox1.isSelected();
        for(int i=0; i<jTable1.getRowCount(); i++)
        {
            jTable1.setValueAt(tots, i, 0);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    
    private void refresh()
    {
        
        while(jTable1.getRowCount()>0)
        {
            modelTable1.removeRow(0);
        }
            
        //Aquesta Select agafa només actuacions que tengui associades dies de sancions
        //ja be, dimecres o expulsio, veure INNER JOIN amb la taula tuta_dies_sancions
        
        String SQL1 = "SELECT "
                + " tuta.id, "
                + " CONCAT(xh.Estudis,' ',xh.Grup) AS grupo, "
                + " CONCAT(xes.Llinatge1,' ',xes.Llinatge2, ', ',xes.Nom1) AS nombre, "
                + " tac.actuacio, "
                + " DATE_FORMAT(tuta.data1, '%d-%m-%Y') as data1, "
                + " DATE_FORMAT(tdies.fins, '%d-%m-%Y') as fins,"
                + " tdies.tipus "
                + " FROM "
                + " tuta_reg_actuacions AS tuta  "
                + " INNER JOIN "
                + " tuta_dies_sancions AS tdies  "
                + " ON tuta.id = tdies.idActuacio  "
                + " INNER JOIN `"+CoreCfg.core_mysqlDBPrefix+"`.xes_alumne AS xes  "
                + " ON xes.Exp2 = tuta.exp2 "
                + " INNER JOIN `"+CoreCfg.core_mysqlDBPrefix+"`.xes_alumne_historic AS xh "
                + " ON xh.Exp2 = xes.Exp2 AND xh.AnyAcademic='" + StringUtils.anyAcademic_primer() + "' "
                + " LEFT JOIN "
                + " tuta_actuacions AS tac "
                + " ON tac.id = tuta.idActuacio "
                + " WHERE tuta.data2 IS NULL  "
                + " AND fins <= (CURRENT_DATE() - INTERVAL 15 DAY) "
                + " ORDER BY tdies.fins,grupo,nombre ";
        
        int casos = 0;
         try {
            Statement st = cfg.getCoreCfg().getMysql().createStatement();
            ResultSet rs1 = cfg.getCoreCfg().getMysql().getResultSet(SQL1,st);
            while(rs1!=null && rs1.next())
            {
              modelTable1.addRow( new Object[]{true, rs1.getInt("id"), 
                    rs1.getString("grupo"),rs1.getString("nombre"),rs1.getString("tipus")+" - "+rs1.getString("actuacio"), rs1.getString("data1"),rs1.getString("fins")});                   
              casos += 1;
            }
            if(rs1!=null) {
                 rs1.close();
                 st.close();
             }
         } catch (SQLException ex) {
            Logger.getLogger(Cleaner.class.getName()).log(Level.SEVERE, null, ex);
         }
         
        
        //Si hi ha alguna actuacio 99 = permís sortida centre oberta cal que es tanqui
        SQL1 = "SELECT "
                + " tuta.id, "
                + " CONCAT(xh.Estudis,' ',xh.Grup) AS grupo, "
                + " CONCAT(xes.Llinatge1,' ',xes.Llinatge2, ', ',xes.Nom1) AS nombre, "
                + " tac.actuacio, "
                + " DATE_FORMAT(tuta.data1, '%d-%m-%Y') as data1 "
                + " FROM "
                + " tuta_reg_actuacions AS tuta  "
                + " INNER JOIN `"+CoreCfg.core_mysqlDBPrefix+"`.xes_alumne AS xes  "
                + " ON xes.Exp2 = tuta.exp2 "
                + " INNER JOIN `"+CoreCfg.core_mysqlDBPrefix+"`.xes_alumne_historic AS xh "
                + " ON xh.Exp2 = xes.Exp2 AND xh.AnyAcademic='" + StringUtils.anyAcademic_primer() + "' "
                + " LEFT JOIN "
                + " tuta_actuacions AS tac "
                + " ON tac.id = tuta.idActuacio "
                + " WHERE tuta.data2 IS NULL  "
                + " AND tuta.idActuacio=99 "
                + " ORDER BY grupo,nombre ";
        
//        //System.out.println("SQL1:"+SQL1);
       
        try {
            Statement st = cfg.getCoreCfg().getMysql().createStatement();
            ResultSet rs1 = cfg.getCoreCfg().getMysql().getResultSet(SQL1,st);
            while(rs1!=null && rs1.next())
            {
              modelTable1.addRow( new Object[]{true, rs1.getInt("id"), 
                    rs1.getString("grupo"),rs1.getString("nombre"), rs1.getString("actuacio"), rs1.getString("data1"), "---"});                   
              casos += 1;
            }
            if(rs1!=null) {
                rs1.close();
                st.close();
            }
         } catch (SQLException ex) {
            Logger.getLogger(Cleaner.class.getName()).log(Level.SEVERE, null, ex);
         }
         
        
        if(casos>0) { 
            jLabel4.setText("Cal que reviseu aquestes "+casos+" actuacions...");
        }
        else {
            jLabel4.setText("L'estat de les actuacions és correcte");
        }
    }
    
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
